name: Docker Images

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-amd64:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Login To GitHub Container Registry
      - name: Log in to the Container GHCR registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: fastapi/Dockerfile
          context: "{{defaultContext}}:."
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/mahdi-b/sagekernelserver:amd64
          labels: ${{ steps.meta.outputs.labels }}

  build-and-push-arm64:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Login To GitHub Container Registry
      - name: Log in to the Container GHCR registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: fastapi/Dockerfile
          context: "{{defaultContext}}:."
          platforms: linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/mahdi-b/sagekernelserver:arm64
          labels: ${{ steps.meta.outputs.labels }}
